ci:
  skip: [fmt, cargo-check]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: mixed-line-ending
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.0.0a2
  hooks:
    - id: sqlfluff-fix
      args: ["--dialect", "postgres"]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
      name: cargo fmt
    - id: cargo-check
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.8.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
