[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.6.20", features = ["http2", "tracing"] }
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
config = "0.13.3"
derive-getters = "0.3.0"
duplicate = "1.0.0"
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.3", features = ["trace"] }
tracing = "0.1.37"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = [
  "env-filter",
  "registry",
] }
uuid = { version = "1.4.1", features = ["v4"] }

[dependencies.sqlx]
version = "0.7"
default-features = false
features = [
  "runtime-tokio-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
]

[dev-dependencies]
hyper = "0.14.27"
once_cell = "1.18.0"
reqwest = "0.11.20"
rstest = "0.18.2"
