application:
  port: 8000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
redis:
  host: "127.0.0.1"
  port: 6379
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
email_client:
  base_url: "https://localhost:8000/"
  sender: "test@example.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
